services:
  redis:
    image: redis:7.4-alpine
    container_name: bip110-cache
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "128mb", "--maxmemory-policy", "allkeys-lru"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  bitcoind-main:
    image: lncm/bitcoind:v26.0
    container_name: bitcoind-main
    ports:
      - "18443:18443"
      - "18445:18444" # P2P port
    command:
      - -regtest=1
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=user
      - -rpcpassword=password
      - -server=1
      - -txindex=1
      - -fallbackfee=0.0001

  bitcoind-bip110:
    image: ghcr.io/retropex/bitcoin:29.3.knots20260210-bip110-v0.4.1
    container_name: bitcoind-bip110
    ports:
      - "18444:18443" # RPC port
      - "18446:18444" # P2P port
    command:
      - -regtest=1
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -rpcuser=user
      - -rpcpassword=password
      - -server=1
      - -txindex=1
      - -fallbackfee=0.0001
      - -vbparams=reduced_data:-1:999999999999
